[package]
name = "abstract-cw1-whitelist"
version = "3.0.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Implementation of an proxy contract using a whitelist"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []
test-utils = []

[dependencies]
abstract-cw1     = { version = "1.2.2", path = "../../packages/cw1" }
abstract-cw2     = { version = "1.2.2", path = "../../packages/cw2" }
cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp", features = ["staking"] }
cw-orch          = { workspace = true }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "zk-mvp" }
cw-utils = { git = "https://github.com/permissionlessweb/cw-minus", branch = "zk-mvp" }
schemars         = { version = "0.8.22" }
serde            = { version = "1.0.219", default-features = false, features = ["derive"] }
thiserror        = { version = "1.0.69" }

[dev-dependencies]
anyhow           = { version = "1" }
assert_matches   = { version = "1" }
cw-multi-test = { package = "abstract-cw-multi-test", git = "https://github.com/permissionlessweb/cw-multi-test-fork", branch = "zk-mvp" }
derivative       = { version = "2" }
easy-addr        = { workspace = true }
