[package]
name = "abstract-cw1-whitelist"
version = "3.0.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Implementation of an proxy contract using a whitelist"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []
test-utils = []

[dependencies]
cosmwasm-schema  = { version = "3.0.4" }
cw-utils         = { path = "../../../cw-minus/packages/cw-utils" }
abstract-cw1     = { version = "1.2.2", path = "../../packages/cw1" }
abstract-cw2     = { version = "1.2.2", path = "../../packages/cw2" }
cosmwasm-std     = { version = "3.0.4", features = ["staking"] }
cw-storage-plus  = { version = "3.0.1" }
schemars         = { version = "0.8.22" }
serde            = { version = "1.0.219", default-features = false, features = ["derive"] }
thiserror        = { version = "1.0.69" }
cw-orch          = { workspace = true }

[dev-dependencies]
easy-addr        = { workspace = true }
anyhow           = { version = "1" }
assert_matches   = { version = "1" }
cw-multi-test    = { version = "3.0.1" }
derivative       = { version = "2" }
