[package]
name = "abstract-cw3-flex-multisig"
version = "3.0.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Implementing cw3 with multiple voting patterns and dynamic groups"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[lib]
crate-type = ["cdylib", "rlib"]

[features]

# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema           = { version = "3.0.0" }
cw-utils                  = { version = "3.0.0" }
abstract-cw2              = { version = "1.2.2", path = "../../packages/cw2" }
abstract-cw3              = { version = "3.0.0", path = "../../packages/cw3" }
abstract-cw3-fixed-multisig = { version = "3.0.0", path = "../cw3-fixed-multisig", features = ["library"] }
abstract-cw4              = { version = "1.2.2", path = "../../packages/cw4" }
abstract-cw20             = { version = "3.0.0", path = "../../packages/cw20" }
cw-storage-plus           = { version = "3.0.0" }
cosmwasm-std              = { version = "3.0.0" }
schemars                  = { version = "0.8.4" }
serde                     = { version = "1.0.219", default-features = false, features = ["derive"] }
thiserror                 = { version = "1.0.69" }
cw-orch                   = { workspace = true }

[dev-dependencies]
abstract-cw4-group       = { version = "3.0.0", path = "../cw4-group" }
cw-multi-test            = { version = "3.0.1" }
abstract-cw20-base       = { version = "3.0.0", path = "../cw20-base" }
